# fly.toml for API
app = "youtube-trend-api"
primary_region = "sjc"  # Choose a region close to you

[build]
  dockerfile = "dockerfile.api"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[processes]
  app = "uvicorn src.api.main:app --host 0.0.0.0 --port 8000"